version: "3.9"
services:

  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src/.:/flask-app
      - ./model/.:/flask-app/model
    image: flask-model-app-dev:tag
    expose:
      - "5000"
    networks:
      - no-internet
    restart: always
    entrypoint: ["python", "app.py"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:4000"
    networks:
      - no-internet
      - internet

networks:
  no-internet:
    internal: true
  internet: {}
